export const glossaryTerms = {
  'mean-time-to-resolution': {
    term: 'Mean Time to Resolution (MTTR)',
    slug: '/glossary/mean-time-to-resolution',
    definition: 'Mean Time to Resolution measures the average time from when a support ticket is created to when it is fully resolved. For B2B technical support, MTTR is the primary metric that drives customer satisfaction and retention.',
    context: 'B2B SaaS companies typically see MTTR of 4-24 hours for technical tickets. The investigation phase — checking logs, querying databases, and cross-referencing systems — accounts for 60-80% of total resolution time.',
    howAltorHelps: 'Altor reduces the investigation phase from 20-45 minutes to under 2 minutes by automatically querying ClickHouse, Linear, Stripe, and GitHub when a ticket arrives.',
    relatedTerms: ['first-response-time', 'support-escalation-rate', 'ticket-investigation'],
    faqs: [
      { q: 'What is a good MTTR for B2B support?', a: 'For B2B SaaS, under 4 hours is excellent, 4-8 hours is good, and over 24 hours indicates investigation bottlenecks.' },
      { q: 'How do you reduce MTTR?', a: 'The biggest lever is automating ticket investigation. Manual log checking takes 20-45 minutes per ticket — automating this cuts MTTR by 40-60%.' },
    ],
  },
  'first-response-time': {
    term: 'First Response Time (FRT)',
    slug: '/glossary/first-response-time',
    definition: 'First Response Time measures how long a customer waits between submitting a support ticket and receiving their first human response. It is the most visible support metric from the customer\'s perspective.',
    context: 'Industry benchmarks show that B2B customers expect a first response within 1-4 hours during business hours. FRT under 1 hour correlates with 20% higher CSAT scores.',
    howAltorHelps: 'Altor provides investigation results before a human agent even reads the ticket, enabling agents to respond with diagnostic data in their first reply instead of asking clarifying questions.',
    relatedTerms: ['mean-time-to-resolution', 'customer-satisfaction-score', 'support-escalation-rate'],
    faqs: [
      { q: 'What is a good first response time for B2B support?', a: 'Under 1 hour is excellent for B2B. Under 4 hours is the industry standard. Anything over 8 hours risks customer escalation.' },
      { q: 'Does faster first response improve resolution time?', a: 'Yes — when the first response includes diagnostic data rather than clarifying questions, the entire resolution cycle shortens by 30-50%.' },
    ],
  },
  'support-escalation-rate': {
    term: 'Support Escalation Rate',
    slug: '/glossary/support-escalation-rate',
    definition: 'Support escalation rate is the percentage of tickets that get escalated from frontline support to engineering, senior agents, or management. High escalation rates indicate that L1 agents lack the tools or data to resolve technical issues.',
    context: 'B2B technical support teams typically see escalation rates of 15-40%. The primary cause is that investigating technical issues requires access to production systems that support agents cannot query directly.',
    howAltorHelps: 'By automatically investigating tickets before they reach an agent, Altor gives L1 agents the same diagnostic data that engineers have, reducing escalations by up to 70%.',
    relatedTerms: ['mean-time-to-resolution', 'ticket-investigation', 'tiered-support-model'],
    faqs: [
      { q: 'What is a good escalation rate?', a: 'Under 15% is excellent for B2B technical support. 15-25% is typical. Over 30% means your L1 team needs better investigation tools.' },
      { q: 'Why do technical tickets get escalated?', a: 'The #1 reason is lack of access to production data. L1 agents can see the ticket but cannot check logs, billing systems, or bug trackers to diagnose the issue.' },
    ],
  },
  'ticket-investigation': {
    term: 'Ticket Investigation',
    slug: '/glossary/ticket-investigation',
    definition: 'Ticket investigation is the process of diagnosing the root cause of a customer-reported issue by querying multiple internal systems — application logs, databases, billing platforms, bug trackers, and monitoring tools.',
    context: 'Unlike consumer support where agents follow scripts, B2B technical investigation requires querying 3-6 different systems per ticket. Each investigation takes 20-45 minutes manually and requires production-level system access.',
    howAltorHelps: 'Altor automates the entire investigation workflow — connecting to ClickHouse, Linear, Stripe, GitHub, and other systems to deliver a root-cause diagnosis in under 2 minutes.',
    relatedTerms: ['mean-time-to-resolution', 'root-cause-analysis', 'support-escalation-rate'],
    faqs: [
      { q: 'What is the difference between support investigation and support triage?', a: 'Triage categorizes and routes tickets. Investigation diagnoses root causes by querying production systems. Triage takes seconds; investigation takes 20-45 minutes.' },
      { q: 'Can AI automate support investigation?', a: 'Yes, if the AI can connect to your actual data systems. Unlike chatbots that search docs, investigation AI queries ClickHouse, Stripe, Linear, and other production tools to find what is actually broken.' },
    ],
  },
  'root-cause-analysis': {
    term: 'Root Cause Analysis (RCA)',
    slug: '/glossary/root-cause-analysis',
    definition: 'Root cause analysis in support context is the process of identifying the underlying technical reason for a customer-reported issue, rather than just addressing the symptom.',
    context: 'RCA for B2B support tickets involves correlating data across multiple systems: API logs showing error patterns, deployment history showing recent changes, billing data showing account state, and bug trackers showing known issues.',
    howAltorHelps: 'Altor performs automated RCA by querying all relevant systems simultaneously and correlating the findings into a structured diagnosis with evidence from each data source.',
    relatedTerms: ['ticket-investigation', 'mean-time-to-resolution', 'incident-management'],
    faqs: [
      { q: 'How long does root cause analysis take for support tickets?', a: 'Manual RCA for a technical B2B ticket typically takes 30-60 minutes, as engineers need to check logs, recent deploys, billing state, and known bugs.' },
      { q: 'What is the difference between RCA and troubleshooting?', a: 'Troubleshooting identifies what is broken. RCA identifies why it broke. RCA requires deeper system access and cross-referencing multiple data sources.' },
    ],
  },
  'tiered-support-model': {
    term: 'Tiered Support Model (L1/L2/L3)',
    slug: '/glossary/tiered-support-model',
    definition: 'A tiered support model organizes support teams into levels: L1 (frontline agents handling initial contact), L2 (senior agents with deeper technical knowledge), and L3 (engineering teams handling the most complex issues).',
    context: 'The tiered model was designed for consumer support where L1 resolves most tickets with scripts. In B2B technical support, the model breaks down because 60-80% of tickets require investigation that L1 cannot perform, creating chronic escalation.',
    howAltorHelps: 'Altor eliminates the investigation bottleneck that forces escalation. L1 agents receive automated diagnoses, enabling them to resolve tickets that previously required L2 or L3.',
    relatedTerms: ['support-escalation-rate', 'ticket-investigation', 'first-response-time'],
    faqs: [
      { q: 'Does the tiered support model work for B2B technical support?', a: 'Poorly. L1 agents cannot investigate production issues, so 30-40% of tickets get escalated regardless of agent skill. The bottleneck is data access, not knowledge.' },
      { q: 'What is the alternative to tiered support?', a: 'Swarming (all agents handle all tickets) combined with investigation automation. When every agent has automated access to diagnostic data, the tier distinction becomes unnecessary.' },
    ],
  },
  'customer-satisfaction-score': {
    term: 'Customer Satisfaction Score (CSAT)',
    slug: '/glossary/customer-satisfaction-score',
    definition: 'CSAT measures customer satisfaction with a specific support interaction, typically on a 1-5 scale collected via post-resolution survey.',
    context: 'In B2B support, CSAT is most strongly correlated with resolution speed and technical accuracy of the answer. Customers who receive root-cause diagnoses in their first response score 20-30% higher on CSAT.',
    howAltorHelps: 'By providing agents with automated investigation results before they respond, Altor enables technically accurate first responses that drive higher CSAT scores.',
    relatedTerms: ['first-response-time', 'net-promoter-score', 'mean-time-to-resolution'],
    faqs: [
      { q: 'What is a good CSAT score for B2B support?', a: 'Above 90% is excellent, 80-90% is good, below 80% indicates systemic issues. Technical accuracy matters more than speed for B2B CSAT.' },
      { q: 'What drives CSAT in B2B technical support?', a: 'Three factors: speed of resolution, technical accuracy of the answer, and whether the customer had to repeat themselves across escalation tiers.' },
    ],
  },
  'support-automation': {
    term: 'Support Automation',
    slug: '/glossary/support-automation',
    definition: 'Support automation uses software to handle parts of the support workflow without human intervention. This ranges from chatbots answering FAQs to AI systems investigating technical issues by querying production databases.',
    context: 'Most support automation focuses on deflection — routing tickets or suggesting help articles. B2B technical support requires investigation automation — AI that can query ClickHouse, check Linear for bugs, and cross-reference Stripe billing data.',
    howAltorHelps: 'Altor is investigation automation, not deflection automation. It queries your actual production systems to deliver root-cause diagnoses, handling the 80% of B2B tickets that chatbots and article-suggestion tools cannot.',
    relatedTerms: ['ticket-investigation', 'support-escalation-rate', 'ai-support-agent'],
    faqs: [
      { q: 'Can AI fully automate B2B technical support?', a: 'Not yet. AI can automate the investigation phase (querying logs, billing, bug trackers) which accounts for 60-80% of resolution time. Human judgment is still needed for communication and edge cases.' },
      { q: 'What is the difference between support automation and chatbots?', a: 'Chatbots search documentation and deflect simple questions. Support automation investigates by querying production systems. Chatbots handle FAQs; automation handles technical issues.' },
    ],
  },
  'ai-support-agent': {
    term: 'AI Support Agent',
    slug: '/glossary/ai-support-agent',
    definition: 'An AI support agent is software that handles support interactions autonomously, from reading tickets to investigating issues to drafting responses. Unlike chatbots, AI support agents connect to production systems.',
    context: 'The term covers a spectrum: from chatbots that suggest articles, to copilots that help agents draft responses, to autonomous agents that investigate and resolve tickets end-to-end. The key differentiator is whether the AI can access your actual data.',
    howAltorHelps: 'Altor is an AI investigation agent — it reads ticket context, queries your production systems (ClickHouse, Linear, Stripe, GitHub), and delivers structured root-cause diagnoses that human agents review and send.',
    relatedTerms: ['support-automation', 'ticket-investigation', 'support-escalation-rate'],
    faqs: [
      { q: 'What is the difference between an AI support agent and a chatbot?', a: 'A chatbot searches your help center. An AI support agent queries your production logs, bug tracker, and billing system to investigate what is actually broken.' },
      { q: 'Can an AI support agent replace human agents?', a: 'Not for B2B technical support. AI handles investigation (querying systems, correlating data). Humans handle communication, judgment calls, and relationship management.' },
    ],
  },
  'incident-management': {
    term: 'Incident Management',
    slug: '/glossary/incident-management',
    definition: 'Incident management is the process of detecting, responding to, and resolving service disruptions. In B2B SaaS, incidents often surface first through customer support tickets before monitoring alerts.',
    context: '30-50% of B2B incidents are first reported by customers, not internal monitoring. Support teams need the same system access as on-call engineers to quickly determine whether a customer report indicates a widespread incident.',
    howAltorHelps: 'When a ticket arrives, Altor checks production metrics and error rates across the customer base — not just the reporting customer — to quickly identify whether the issue is isolated or an incident.',
    relatedTerms: ['root-cause-analysis', 'ticket-investigation', 'mean-time-to-resolution'],
    faqs: [
      { q: 'How does support relate to incident management?', a: 'Support teams are often the first to detect incidents through customer reports. Fast investigation determines whether a ticket is an isolated issue or a widespread incident requiring engineering response.' },
      { q: 'What is the average cost of a B2B SaaS incident?', a: 'For mid-market SaaS, a P1 incident costs $5,000-50,000 per hour in revenue impact, customer trust erosion, and engineering time. Faster detection through support reduces total impact.' },
    ],
  },
  'net-promoter-score': {
    term: 'Net Promoter Score (NPS)',
    slug: '/glossary/net-promoter-score',
    definition: 'NPS measures customer loyalty by asking how likely they are to recommend your product (0-10 scale). Promoters (9-10) minus Detractors (0-6) equals your NPS.',
    context: 'B2B SaaS NPS is heavily influenced by support quality. Companies with sub-4-hour MTTR average 15-20 points higher NPS than those with 24+ hour MTTR. Support is the most common interaction that moves a customer from Promoter to Detractor.',
    howAltorHelps: 'By reducing investigation time from 20-45 minutes to under 2 minutes, Altor shortens MTTR which directly improves NPS. Customers who get fast, accurate resolutions become promoters.',
    relatedTerms: ['customer-satisfaction-score', 'mean-time-to-resolution', 'first-response-time'],
    faqs: [
      { q: 'What is a good NPS for B2B SaaS?', a: 'Above 50 is excellent, 30-50 is good, 0-30 is average. Support quality is the #1 operational driver of NPS in B2B.' },
      { q: 'How does support quality affect NPS?', a: 'A single bad support experience can drop a Promoter to a Detractor (-20 point swing). Conversely, resolving a complex issue quickly often converts Passives to Promoters.' },
    ],
  },
  'sla-service-level-agreement': {
    term: 'Service Level Agreement (SLA)',
    slug: '/glossary/sla-service-level-agreement',
    definition: 'An SLA defines the committed response and resolution times for different ticket priorities. SLA breaches result in service credits, penalty fees, or contract termination in B2B agreements.',
    context: 'Enterprise B2B SLAs typically require P1 response within 15-30 minutes and resolution within 4 hours. SLA compliance directly affects revenue — a single enterprise SLA breach can cost $10,000-100,000 in credits.',
    howAltorHelps: 'Altor helps meet SLA targets by starting investigation the moment a ticket arrives, rather than when an agent picks it up. This eliminates the queue-to-investigation gap that causes most SLA breaches.',
    relatedTerms: ['mean-time-to-resolution', 'first-response-time', 'incident-management'],
    faqs: [
      { q: 'What are typical B2B SaaS SLA targets?', a: 'P1: 15 min response, 4 hr resolution. P2: 1 hr response, 8 hr resolution. P3: 4 hr response, 24 hr resolution. P4: 8 hr response, 72 hr resolution.' },
      { q: 'What happens when you breach an SLA?', a: 'Contractually: service credits (typically 5-25% of monthly fee per breach). Practically: eroded customer trust, increased churn risk, and escalation to executive sponsors.' },
    ],
  },
}
