export const glossaryTerms = {
  'mean-time-to-resolution': {
    term: 'Mean Time to Resolution (MTTR)',
    slug: '/glossary/mean-time-to-resolution',
    definition: 'Mean Time to Resolution measures the average time from when a support ticket is created to when it is fully resolved. For B2B technical support, MTTR is the primary metric that drives customer satisfaction and retention.',
    context: 'B2B SaaS companies typically see MTTR of 4-24 hours for technical tickets. The investigation phase — checking logs, querying databases, and cross-referencing systems — accounts for 60-80% of total resolution time.',
    howAltorHelps: 'Altor reduces the investigation phase from 20-45 minutes to under 2 minutes by automatically querying ClickHouse, Linear, Stripe, and GitHub when a ticket arrives.',
    relatedTerms: ['first-response-time', 'support-escalation-rate', 'ticket-investigation'],
    faqs: [
      { q: 'What is a good MTTR for B2B support?', a: 'For B2B SaaS, under 4 hours is excellent, 4-8 hours is good, and over 24 hours indicates investigation bottlenecks.' },
      { q: 'How do you reduce MTTR?', a: 'The biggest lever is automating ticket investigation. Manual log checking takes 20-45 minutes per ticket — automating this cuts MTTR by 40-60%.' },
    ],
  },
  'first-response-time': {
    term: 'First Response Time (FRT)',
    slug: '/glossary/first-response-time',
    definition: 'First Response Time measures how long a customer waits between submitting a support ticket and receiving their first human response. It is the most visible support metric from the customer\'s perspective.',
    context: 'Industry benchmarks show that B2B customers expect a first response within 1-4 hours during business hours. FRT under 1 hour correlates with 20% higher CSAT scores.',
    howAltorHelps: 'Altor provides investigation results before a human agent even reads the ticket, enabling agents to respond with diagnostic data in their first reply instead of asking clarifying questions.',
    relatedTerms: ['mean-time-to-resolution', 'customer-satisfaction-score', 'support-escalation-rate'],
    faqs: [
      { q: 'What is a good first response time for B2B support?', a: 'Under 1 hour is excellent for B2B. Under 4 hours is the industry standard. Anything over 8 hours risks customer escalation.' },
      { q: 'Does faster first response improve resolution time?', a: 'Yes — when the first response includes diagnostic data rather than clarifying questions, the entire resolution cycle shortens by 30-50%.' },
    ],
  },
  'support-escalation-rate': {
    term: 'Support Escalation Rate',
    slug: '/glossary/support-escalation-rate',
    definition: 'Support escalation rate is the percentage of tickets that get escalated from frontline support to engineering, senior agents, or management. High escalation rates indicate that L1 agents lack the tools or data to resolve technical issues.',
    context: 'B2B technical support teams typically see escalation rates of 15-40%. The primary cause is that investigating technical issues requires access to production systems that support agents cannot query directly.',
    howAltorHelps: 'By automatically investigating tickets before they reach an agent, Altor gives L1 agents the same diagnostic data that engineers have, reducing escalations by up to 70%.',
    relatedTerms: ['mean-time-to-resolution', 'ticket-investigation', 'tiered-support-model'],
    faqs: [
      { q: 'What is a good escalation rate?', a: 'Under 15% is excellent for B2B technical support. 15-25% is typical. Over 30% means your L1 team needs better investigation tools.' },
      { q: 'Why do technical tickets get escalated?', a: 'The #1 reason is lack of access to production data. L1 agents can see the ticket but cannot check logs, billing systems, or bug trackers to diagnose the issue.' },
    ],
  },
  'ticket-investigation': {
    term: 'Ticket Investigation',
    slug: '/glossary/ticket-investigation',
    definition: 'Ticket investigation is the process of diagnosing the root cause of a customer-reported issue by querying multiple internal systems — application logs, databases, billing platforms, bug trackers, and monitoring tools.',
    context: 'Unlike consumer support where agents follow scripts, B2B technical investigation requires querying 3-6 different systems per ticket. Each investigation takes 20-45 minutes manually and requires production-level system access.',
    howAltorHelps: 'Altor automates the entire investigation workflow — connecting to ClickHouse, Linear, Stripe, GitHub, and other systems to deliver a root-cause diagnosis in under 2 minutes.',
    relatedTerms: ['mean-time-to-resolution', 'root-cause-analysis', 'support-escalation-rate'],
    faqs: [
      { q: 'What is the difference between support investigation and support triage?', a: 'Triage categorizes and routes tickets. Investigation diagnoses root causes by querying production systems. Triage takes seconds; investigation takes 20-45 minutes.' },
      { q: 'Can AI automate support investigation?', a: 'Yes, if the AI can connect to your actual data systems. Unlike chatbots that search docs, investigation AI queries ClickHouse, Stripe, Linear, and other production tools to find what is actually broken.' },
    ],
  },
  'root-cause-analysis': {
    term: 'Root Cause Analysis (RCA)',
    slug: '/glossary/root-cause-analysis',
    definition: 'Root cause analysis in support context is the process of identifying the underlying technical reason for a customer-reported issue, rather than just addressing the symptom.',
    context: 'RCA for B2B support tickets involves correlating data across multiple systems: API logs showing error patterns, deployment history showing recent changes, billing data showing account state, and bug trackers showing known issues.',
    howAltorHelps: 'Altor performs automated RCA by querying all relevant systems simultaneously and correlating the findings into a structured diagnosis with evidence from each data source.',
    relatedTerms: ['ticket-investigation', 'mean-time-to-resolution', 'incident-management'],
    faqs: [
      { q: 'How long does root cause analysis take for support tickets?', a: 'Manual RCA for a technical B2B ticket typically takes 30-60 minutes, as engineers need to check logs, recent deploys, billing state, and known bugs.' },
      { q: 'What is the difference between RCA and troubleshooting?', a: 'Troubleshooting identifies what is broken. RCA identifies why it broke. RCA requires deeper system access and cross-referencing multiple data sources.' },
    ],
  },
  'tiered-support-model': {
    term: 'Tiered Support Model (L1/L2/L3)',
    slug: '/glossary/tiered-support-model',
    definition: 'A tiered support model organizes support teams into levels: L1 (frontline agents handling initial contact), L2 (senior agents with deeper technical knowledge), and L3 (engineering teams handling the most complex issues).',
    context: 'The tiered model was designed for consumer support where L1 resolves most tickets with scripts. In B2B technical support, the model breaks down because 60-80% of tickets require investigation that L1 cannot perform, creating chronic escalation.',
    howAltorHelps: 'Altor eliminates the investigation bottleneck that forces escalation. L1 agents receive automated diagnoses, enabling them to resolve tickets that previously required L2 or L3.',
    relatedTerms: ['support-escalation-rate', 'ticket-investigation', 'first-response-time'],
    faqs: [
      { q: 'Does the tiered support model work for B2B technical support?', a: 'Poorly. L1 agents cannot investigate production issues, so 30-40% of tickets get escalated regardless of agent skill. The bottleneck is data access, not knowledge.' },
      { q: 'What is the alternative to tiered support?', a: 'Swarming (all agents handle all tickets) combined with investigation automation. When every agent has automated access to diagnostic data, the tier distinction becomes unnecessary.' },
    ],
  },
  'customer-satisfaction-score': {
    term: 'Customer Satisfaction Score (CSAT)',
    slug: '/glossary/customer-satisfaction-score',
    definition: 'CSAT measures customer satisfaction with a specific support interaction, typically on a 1-5 scale collected via post-resolution survey.',
    context: 'In B2B support, CSAT is most strongly correlated with resolution speed and technical accuracy of the answer. Customers who receive root-cause diagnoses in their first response score 20-30% higher on CSAT.',
    howAltorHelps: 'By providing agents with automated investigation results before they respond, Altor enables technically accurate first responses that drive higher CSAT scores.',
    relatedTerms: ['first-response-time', 'net-promoter-score', 'mean-time-to-resolution'],
    faqs: [
      { q: 'What is a good CSAT score for B2B support?', a: 'Above 90% is excellent, 80-90% is good, below 80% indicates systemic issues. Technical accuracy matters more than speed for B2B CSAT.' },
      { q: 'What drives CSAT in B2B technical support?', a: 'Three factors: speed of resolution, technical accuracy of the answer, and whether the customer had to repeat themselves across escalation tiers.' },
    ],
  },
  'support-automation': {
    term: 'Support Automation',
    slug: '/glossary/support-automation',
    definition: 'Support automation uses software to handle parts of the support workflow without human intervention. This ranges from chatbots answering FAQs to AI systems investigating technical issues by querying production databases.',
    context: 'Most support automation focuses on deflection — routing tickets or suggesting help articles. B2B technical support requires investigation automation — AI that can query ClickHouse, check Linear for bugs, and cross-reference Stripe billing data.',
    howAltorHelps: 'Altor is investigation automation, not deflection automation. It queries your actual production systems to deliver root-cause diagnoses, handling the 80% of B2B tickets that chatbots and article-suggestion tools cannot.',
    relatedTerms: ['ticket-investigation', 'support-escalation-rate', 'ai-support-agent'],
    faqs: [
      { q: 'Can AI fully automate B2B technical support?', a: 'Not yet. AI can automate the investigation phase (querying logs, billing, bug trackers) which accounts for 60-80% of resolution time. Human judgment is still needed for communication and edge cases.' },
      { q: 'What is the difference between support automation and chatbots?', a: 'Chatbots search documentation and deflect simple questions. Support automation investigates by querying production systems. Chatbots handle FAQs; automation handles technical issues.' },
    ],
  },
  'ai-support-agent': {
    term: 'AI Support Agent',
    slug: '/glossary/ai-support-agent',
    definition: 'An AI support agent is software that handles support interactions autonomously, from reading tickets to investigating issues to drafting responses. Unlike chatbots, AI support agents connect to production systems.',
    context: 'The term covers a spectrum: from chatbots that suggest articles, to copilots that help agents draft responses, to autonomous agents that investigate and resolve tickets end-to-end. The key differentiator is whether the AI can access your actual data.',
    howAltorHelps: 'Altor is an AI investigation agent — it reads ticket context, queries your production systems (ClickHouse, Linear, Stripe, GitHub), and delivers structured root-cause diagnoses that human agents review and send.',
    relatedTerms: ['support-automation', 'ticket-investigation', 'support-escalation-rate'],
    faqs: [
      { q: 'What is the difference between an AI support agent and a chatbot?', a: 'A chatbot searches your help center. An AI support agent queries your production logs, bug tracker, and billing system to investigate what is actually broken.' },
      { q: 'Can an AI support agent replace human agents?', a: 'Not for B2B technical support. AI handles investigation (querying systems, correlating data). Humans handle communication, judgment calls, and relationship management.' },
    ],
  },
  'incident-management': {
    term: 'Incident Management',
    slug: '/glossary/incident-management',
    definition: 'Incident management is the process of detecting, responding to, and resolving service disruptions. In B2B SaaS, incidents often surface first through customer support tickets before monitoring alerts.',
    context: '30-50% of B2B incidents are first reported by customers, not internal monitoring. Support teams need the same system access as on-call engineers to quickly determine whether a customer report indicates a widespread incident.',
    howAltorHelps: 'When a ticket arrives, Altor checks production metrics and error rates across the customer base — not just the reporting customer — to quickly identify whether the issue is isolated or an incident.',
    relatedTerms: ['root-cause-analysis', 'ticket-investigation', 'mean-time-to-resolution'],
    faqs: [
      { q: 'How does support relate to incident management?', a: 'Support teams are often the first to detect incidents through customer reports. Fast investigation determines whether a ticket is an isolated issue or a widespread incident requiring engineering response.' },
      { q: 'What is the average cost of a B2B SaaS incident?', a: 'For mid-market SaaS, a P1 incident costs $5,000-50,000 per hour in revenue impact, customer trust erosion, and engineering time. Faster detection through support reduces total impact.' },
    ],
  },
  'net-promoter-score': {
    term: 'Net Promoter Score (NPS)',
    slug: '/glossary/net-promoter-score',
    definition: 'NPS measures customer loyalty by asking how likely they are to recommend your product (0-10 scale). Promoters (9-10) minus Detractors (0-6) equals your NPS.',
    context: 'B2B SaaS NPS is heavily influenced by support quality. Companies with sub-4-hour MTTR average 15-20 points higher NPS than those with 24+ hour MTTR. Support is the most common interaction that moves a customer from Promoter to Detractor.',
    howAltorHelps: 'By reducing investigation time from 20-45 minutes to under 2 minutes, Altor shortens MTTR which directly improves NPS. Customers who get fast, accurate resolutions become promoters.',
    relatedTerms: ['customer-satisfaction-score', 'mean-time-to-resolution', 'first-response-time'],
    faqs: [
      { q: 'What is a good NPS for B2B SaaS?', a: 'Above 50 is excellent, 30-50 is good, 0-30 is average. Support quality is the #1 operational driver of NPS in B2B.' },
      { q: 'How does support quality affect NPS?', a: 'A single bad support experience can drop a Promoter to a Detractor (-20 point swing). Conversely, resolving a complex issue quickly often converts Passives to Promoters.' },
    ],
  },
  'sla-service-level-agreement': {
    term: 'Service Level Agreement (SLA)',
    slug: '/glossary/sla-service-level-agreement',
    definition: 'An SLA defines the committed response and resolution times for different ticket priorities. SLA breaches result in service credits, penalty fees, or contract termination in B2B agreements.',
    context: 'Enterprise B2B SLAs typically require P1 response within 15-30 minutes and resolution within 4 hours. SLA compliance directly affects revenue — a single enterprise SLA breach can cost $10,000-100,000 in credits.',
    howAltorHelps: 'Altor helps meet SLA targets by starting investigation the moment a ticket arrives, rather than when an agent picks it up. This eliminates the queue-to-investigation gap that causes most SLA breaches.',
    relatedTerms: ['mean-time-to-resolution', 'first-response-time', 'incident-management'],
    faqs: [
      { q: 'What are typical B2B SaaS SLA targets?', a: 'P1: 15 min response, 4 hr resolution. P2: 1 hr response, 8 hr resolution. P3: 4 hr response, 24 hr resolution. P4: 8 hr response, 72 hr resolution.' },
      { q: 'What happens when you breach an SLA?', a: 'Contractually: service credits (typically 5-25% of monthly fee per breach). Practically: eroded customer trust, increased churn risk, and escalation to executive sponsors.' },
    ],
  },
  'ticket-deflection-rate': {
    term: 'Ticket Deflection Rate',
    slug: '/glossary/ticket-deflection-rate',
    definition: 'Ticket deflection rate measures the percentage of support requests that never become agent-handled tickets because customers solved the issue through self-serve help, product cues, or automation. For B2B teams, deflection is healthy only when it removes low-value questions without hiding unresolved technical incidents.',
    context: 'B2B companies often over-optimize for deflection and accidentally make it harder for paying customers to reach an expert when a real production issue happens. The right goal is to deflect repetitive FAQ traffic while preserving a fast path for urgent technical tickets.',
    howAltorHelps: 'Altor does not try to deflect complex incidents into a help center loop. It lets teams safely deflect simple questions while automatically investigating the tickets that should reach support immediately.',
    stats: [
      { value: '10–25%', label: 'healthy deflection range for technical B2B support' },
      { value: '80%', label: 'of complex tickets that still require live investigation' },
      { value: '2 min', label: 'target diagnosis time once a technical ticket is accepted' },
      { value: '1 route', label: 'clear escalation path customers need for urgent incidents' },
    ],
    relatedTerms: ['support-automation', 'ticket-investigation', 'customer-satisfaction-score'],
    faqs: [
      { q: 'Is a higher ticket deflection rate always better?', a: 'No. In B2B support, very high deflection can mean customers are being pushed away from human help even when they have live production issues.' },
      { q: 'What should teams deflect?', a: 'Deflect repetitive setup, billing FAQ, and documentation questions. Do not deflect tickets that mention outages, failed API calls, or customer-specific production behavior.' },
    ],
  },
  'first-contact-resolution': {
    term: 'First Contact Resolution (FCR)',
    slug: '/glossary/first-contact-resolution',
    definition: 'First Contact Resolution measures the percentage of tickets solved in the first meaningful reply without follow-up handoffs or repeated back-and-forth. In B2B support, true FCR usually depends on whether the first response includes diagnostic evidence, not just empathy and next steps.',
    context: 'Technical support teams struggle with FCR because the first response often asks for logs, account IDs, and screenshots instead of giving an answer. That creates extra cycles, longer queues, and more customer frustration.',
    howAltorHelps: 'Altor investigates before the agent replies, so the first response can include root cause, evidence, and a recommended action instead of a list of clarifying questions.',
    stats: [
      { value: '45–70%', label: 'typical FCR range for mature B2B support teams' },
      { value: '30–50%', label: 'lift possible when first replies include diagnostics' },
      { value: '1 reply', label: 'ideal number of customer touches for common technical issues' },
      { value: '20–45 min', label: 'manual investigation time that usually blocks FCR' },
    ],
    relatedTerms: ['first-response-time', 'mean-time-to-resolution', 'ticket-investigation'],
    faqs: [
      { q: 'Why is FCR hard in B2B technical support?', a: 'Because agents need live system data before they can resolve the issue. Without investigation access, the first reply is usually incomplete.' },
      { q: 'Does FCR matter more than first response time?', a: 'For B2B technical teams, both matter. A fast first response is good, but a fast first response with an actual diagnosis is what improves FCR and customer trust.' },
    ],
  },
  'sla-compliance-rate': {
    term: 'SLA Compliance Rate',
    slug: '/glossary/sla-compliance-rate',
    definition: 'SLA compliance rate is the percentage of tickets resolved within the response and resolution commitments promised in customer contracts. It is one of the clearest support metrics tied directly to retained revenue in enterprise B2B accounts.',
    context: 'A team can miss SLA targets even with talented agents if the investigation phase starts too late. Queue delays and slow data gathering are the biggest hidden causes of enterprise SLA breaches.',
    howAltorHelps: 'Altor starts the investigation immediately when the ticket lands, shrinking the gap between ticket creation and meaningful technical work so more tickets stay inside SLA windows.',
    stats: [
      { value: '95%+', label: 'common enterprise SLA compliance target' },
      { value: '15–30 min', label: 'typical P1 response commitment' },
      { value: '4 hr', label: 'common P1 resolution deadline' },
      { value: '$10K+', label: 'possible impact of a serious enterprise SLA breach' },
    ],
    relatedTerms: ['sla-service-level-agreement', 'mean-time-to-resolution', 'incident-management'],
    faqs: [
      { q: 'What lowers SLA compliance most often?', a: 'Delayed investigation starts, not agent effort. Teams lose time waiting for someone with the right data access to begin diagnosing the issue.' },
      { q: 'How is SLA compliance different from MTTR?', a: 'MTTR measures average resolution time across tickets. SLA compliance measures whether each ticket met a specific contractual target.' },
    ],
  },
  'support-cost-per-ticket': {
    term: 'Support Cost Per Ticket',
    slug: '/glossary/support-cost-per-ticket',
    definition: 'Support cost per ticket measures the fully loaded cost of resolving one support issue, including agent time, engineering escalations, tooling, and overhead. In B2B support, this metric jumps quickly when every technical ticket needs manual log analysis or product-engineering involvement.',
    context: 'Leaders often underestimate this metric because they count support salaries but ignore the hidden cost of engineering interruptions. A ticket that escalates to product or infra teams can cost several times more than it appears in the help desk.',
    howAltorHelps: 'By reducing manual investigation and lowering escalations, Altor cuts the most expensive portion of technical ticket handling: engineering time spent reproducing and diagnosing customer-specific issues.',
    stats: [
      { value: '$15–60', label: 'common cost range for a standard B2B support ticket' },
      { value: '$100+', label: 'cost of tickets that require engineering attention' },
      { value: '60–80%', label: 'share of resolution time often spent investigating' },
      { value: '2 min', label: 'investigation target that improves unit economics' },
    ],
    relatedTerms: ['mean-time-to-resolution', 'support-escalation-rate', 'ticket-investigation'],
    faqs: [
      { q: 'Why is support cost per ticket high in B2B?', a: 'Because technical tickets touch multiple systems and often pull in engineers. The labor cost of investigation is much higher than the visible help desk workflow suggests.' },
      { q: 'How do teams reduce support cost per ticket?', a: 'Automate investigation, reduce escalations, and give frontline agents access to structured diagnostic evidence before they respond.' },
    ],
  },
  'knowledge-base-deflection': {
    term: 'Knowledge Base Deflection',
    slug: '/glossary/knowledge-base-deflection',
    definition: 'Knowledge base deflection measures how often documentation helps a customer solve an issue without creating a support ticket. It is most valuable for onboarding questions, setup steps, and common workflow answers.',
    context: 'For B2B support, documentation works best on predictable questions and weakest on production-specific failures. Teams need to know exactly where the help center stops being useful so technical tickets are not trapped in self-serve loops.',
    howAltorHelps: 'Altor complements the knowledge base by handling the cases docs cannot solve. When customers move from “how do I do this?” to “why did this break for my account?”, Altor takes over the investigation layer.',
    stats: [
      { value: '15–35%', label: 'common deflection range for strong B2B help centers' },
      { value: '0%', label: 'help-center usefulness on customer-specific production incidents' },
      { value: '24/7', label: 'availability advantage of strong documentation' },
      { value: '1 click', label: 'ideal handoff path from docs to support for urgent issues' },
    ],
    relatedTerms: ['ticket-deflection-rate', 'support-automation', 'ai-support-agent'],
    faqs: [
      { q: 'What kinds of issues should a knowledge base deflect?', a: 'Setup instructions, policy questions, product explanations, and repeatable troubleshooting steps are strong candidates for documentation-led deflection.' },
      { q: 'What should not be pushed into docs?', a: 'Live outages, account-specific billing problems, and technical regressions that require log or system access.' },
    ],
  },
  'agent-utilization-rate': {
    term: 'Agent Utilization Rate',
    slug: '/glossary/agent-utilization-rate',
    definition: 'Agent utilization rate measures how much of an agent’s working time is spent on active support work versus idle time, meetings, or admin tasks. In technical support, utilization becomes dangerous when agents are busy but still blocked by manual investigation steps they cannot complete quickly.',
    context: 'High utilization can look efficient on dashboards while customers still wait because every agent is stuck gathering data from logs, bug trackers, and billing tools. Sustainable utilization matters more than maxed-out utilization.',
    howAltorHelps: 'Altor removes repetitive investigation work from the agent queue, which improves productive utilization without forcing agents into constant context switching or escalation chasing.',
    stats: [
      { value: '65–80%', label: 'healthy utilization range for support teams' },
      { value: '85%+', label: 'utilization level where burnout and queue delays rise' },
      { value: '20–45 min', label: 'manual investigation time that inflates utilization' },
      { value: '1 queue', label: 'simpler workflow once investigation is automated' },
    ],
    relatedTerms: ['support-cost-per-ticket', 'mean-time-to-resolution', 'support-escalation-rate'],
    faqs: [
      { q: 'Is higher agent utilization always better?', a: 'No. Very high utilization often means the team has no buffer for spikes, incidents, or complex investigations, which hurts service quality.' },
      { q: 'How do teams improve utilization safely?', a: 'Remove non-value-added work like manual data gathering, give agents faster access to diagnostics, and keep enough capacity for incident surges.' },
    ],
  },
  'customer-effort-score': {
    term: 'Customer Effort Score (CES)',
    slug: '/glossary/customer-effort-score',
    definition: 'Customer Effort Score measures how easy it was for a customer to get their problem solved. In support, CES improves when the customer does not need to repeat context, chase updates, or wait through multiple internal handoffs.',
    context: 'B2B buyers remember effort almost as strongly as outcome. Even when an issue is eventually fixed, a high-effort experience damages renewal confidence and makes executive escalation more likely.',
    howAltorHelps: 'Altor lowers customer effort by giving the support team an evidence-backed diagnosis early, reducing the need for repeated clarification loops and unnecessary transfers to engineering.',
    stats: [
      { value: '1–7', label: 'common CES survey scale' },
      { value: '2–3', label: 'target low-effort score for strong support teams' },
      { value: '3+', label: 'internal handoffs that usually hurt CES' },
      { value: '1 reply', label: 'ideal number of times customers explain the issue' },
    ],
    relatedTerms: ['customer-satisfaction-score', 'first-contact-resolution', 'support-escalation-rate'],
    faqs: [
      { q: 'What increases customer effort most?', a: 'Repeated requests for the same context, slow follow-up, and being transferred between support and engineering without a clear answer.' },
      { q: 'How is CES different from CSAT?', a: 'CES measures how hard the support experience felt. CSAT measures overall satisfaction with the interaction or outcome.' },
    ],
  },
  'proactive-support': {
    term: 'Proactive Support',
    slug: '/glossary/proactive-support',
    definition: 'Proactive support means identifying and addressing customer-impacting issues before the customer opens a ticket. In B2B SaaS, that can include noticing error spikes, failed webhooks, billing anomalies, or rollout regressions before they turn into escalations.',
    context: 'The best B2B teams do not wait for customers to discover every issue first. Proactive communication reduces churn risk because customers see that the vendor is watching, investigating, and responding before they have to chase updates.',
    howAltorHelps: 'Altor helps teams move toward proactive support by detecting patterns across incoming tickets and shared systems, making it easier to see whether a “single ticket” is actually the first sign of a wider problem.',
    stats: [
      { value: '30–50%', label: 'share of incidents first surfaced by customers in B2B SaaS' },
      { value: '1 alert', label: 'signal needed to start proactive outreach fast' },
      { value: '2 min', label: 'investigation window that enables proactive replies' },
      { value: '24 hr', label: 'time saved when customers do not need to discover the issue first' },
    ],
    relatedTerms: ['incident-management', 'ticket-investigation', 'customer-satisfaction-score'],
    faqs: [
      { q: 'What does proactive support look like in practice?', a: 'It means reaching out with a diagnosis or mitigation plan before the customer asks, based on data from logs, billing, or deployment systems.' },
      { q: 'Why is proactive support hard to do manually?', a: 'Because teams need to connect signals across multiple systems fast enough to act before ticket volume spikes.' },
    ],
  },
  'support-quality-score': {
    term: 'Support Quality Score',
    slug: '/glossary/support-quality-score',
    definition: 'Support quality score is an internal measure of how accurate, complete, and policy-compliant support responses are. For technical teams, quality means the answer was not only polite, but actually correct and backed by evidence from the customer’s systems.',
    context: 'B2B support quality drops when agents rely on guesswork or generic playbooks for technical problems. A response can sound professional and still be low quality if it misses the real cause of the issue.',
    howAltorHelps: 'Altor improves quality scores by giving agents structured diagnostic findings they can review before sending. That reduces speculative replies and increases consistency across the team.',
    stats: [
      { value: '85%+', label: 'target internal QA score for mature teams' },
      { value: '2–5', label: 'review criteria often used in support QA rubrics' },
      { value: '1 source', label: 'minimum evidence expected in technical answers' },
      { value: '70%', label: 'quality risk when agents answer before investigating' },
    ],
    relatedTerms: ['customer-satisfaction-score', 'root-cause-analysis', 'first-contact-resolution'],
    faqs: [
      { q: 'What lowers support quality scores most?', a: 'Inaccurate technical answers, missing next steps, and responses that sound polished but do not address the actual issue.' },
      { q: 'How do teams improve quality at scale?', a: 'Use clear QA rubrics, give agents faster access to evidence, and reduce the need to guess when diagnosing customer issues.' },
    ],
  },
  'ticket-backlog': {
    term: 'Ticket Backlog',
    slug: '/glossary/ticket-backlog',
    definition: 'Ticket backlog is the number of unresolved tickets waiting in the queue beyond the team’s normal operating window. In B2B support, backlog is especially dangerous when high-value customers with technical incidents are sitting behind slower investigative work.',
    context: 'Backlogs do not usually start because teams stopped answering tickets; they start because investigation takes too long and complex tickets pile up faster than they are diagnosed. Once backlog grows, first response time, SLA compliance, and CSAT all deteriorate together.',
    howAltorHelps: 'Altor cuts the investigation time that causes technical queues to clog, helping teams clear backlog faster without immediately adding more engineers or restructuring every shift.',
    stats: [
      { value: '1 day', label: 'threshold where backlog starts becoming visible to customers' },
      { value: '20–45 min', label: 'manual investigation time that creates queue pressure' },
      { value: '2x', label: 'backlog growth risk during incidents or launch weeks' },
      { value: '0 breach', label: 'ideal SLA outcome while clearing backlog' },
    ],
    relatedTerms: ['mean-time-to-resolution', 'first-response-time', 'sla-compliance-rate'],
    faqs: [
      { q: 'What usually creates a support backlog?', a: 'A surge of technical tickets plus slow manual investigation. Teams can respond quickly, but they cannot resolve tickets fast enough to shrink the queue.' },
      { q: 'How do teams reduce backlog sustainably?', a: 'Increase investigation speed, prioritize high-risk customers correctly, and automate the diagnostic work that prevents tickets from moving forward.' },
    ],
  },
  'escalation-path': {
    term: 'Escalation Path',
    slug: '/glossary/escalation-path',
    definition: 'An escalation path defines who should handle a support issue when the frontline team cannot resolve it, and in what order the handoff should happen. In B2B technical support, a clear escalation path prevents tickets from bouncing randomly between support, product, and engineering.',
    context: 'Escalation paths break down when nobody knows whether the blocker is billing, a product bug, a usage issue, or an infrastructure incident. Without an early diagnosis, the path becomes guesswork and the customer waits while teams redirect the case internally.',
    howAltorHelps: 'Altor clarifies the escalation path by identifying likely root cause first. That lets teams escalate to the right owner once, with evidence, instead of spreading the same ticket across multiple channels.',
    stats: [
      { value: '1 handoff', label: 'ideal number of escalations for complex tickets' },
      { value: '3 teams', label: 'common number of groups a misrouted B2B ticket touches' },
      { value: '70%', label: 'escalation reduction possible with better diagnosis' },
      { value: '2 min', label: 'time window to classify escalation correctly' },
    ],
    relatedTerms: ['support-escalation-rate', 'tiered-support-model', 'ticket-investigation'],
    faqs: [
      { q: 'What makes an escalation path effective?', a: 'Clear ownership rules, a fast diagnosis step, and a defined expectation for what information must accompany the handoff.' },
      { q: 'Why do escalation paths fail?', a: 'Because teams escalate before they understand the issue. That sends tickets to the wrong owner and forces extra internal back-and-forth.' },
    ],
  },
  'time-to-first-response': {
    term: 'Time to First Response',
    slug: '/glossary/time-to-first-response',
    definition: 'Time to First Response measures how long it takes a customer to receive the first human reply after opening a ticket. It is closely related to first response time, but teams often use this wording in dashboards, customer reports, and executive reviews.',
    context: 'In B2B support, fast first response sets confidence, but empty acknowledgments are not enough. Customers care whether the first reply shows that someone actually understood the problem and started investigating it.',
    howAltorHelps: 'Altor shortens time to first response by preparing a technical diagnosis immediately, allowing agents to send a useful reply faster instead of delaying until they finish manual research.',
    stats: [
      { value: '<1 hr', label: 'excellent first response target for B2B teams' },
      { value: '1–4 hr', label: 'common contract expectation during business hours' },
      { value: '30–50%', label: 'resolution improvement when first replies include data' },
      { value: '0 guesswork', label: 'goal for technical first responses' },
    ],
    relatedTerms: ['first-response-time', 'first-contact-resolution', 'customer-effort-score'],
    faqs: [
      { q: 'Is time to first response the same as first response time?', a: 'Yes in most teams. The two phrases usually refer to the same metric: how long the customer waits for the first reply.' },
      { q: 'What makes a first response actually valuable?', a: 'It should confirm the team has begun investigating, include any early findings, and avoid asking the customer to repeat information already present in the ticket.' },
    ],
  },
  'support-deflection': {
    term: 'Support Deflection',
    slug: '/glossary/support-deflection',
    definition: 'Support deflection is the broader practice of reducing agent-handled ticket volume through self-serve content, in-product guidance, automation, or workflow design. It covers knowledge-base deflection, chatbot routing, and other mechanisms that prevent low-value tickets from reaching humans.',
    context: 'For B2B teams, support deflection is useful only when it protects team capacity without blocking real customer problems. Technical support leaders need a clear line between “deflectable” and “investigation-required” issues.',
    howAltorHelps: 'Altor helps teams practice safer support deflection by taking the complex investigation work off the table. That means you can deflect simple questions confidently while still moving serious tickets into a fast, evidence-based resolution path.',
    stats: [
      { value: '20–40%', label: 'common overall deflection range for mature support programs' },
      { value: '80%', label: 'share of technical tickets that are poor deflection candidates' },
      { value: '1 split', label: 'critical line between FAQ and investigation workflows' },
      { value: '24/7', label: 'self-serve coverage advantage of strong deflection systems' },
    ],
    relatedTerms: ['ticket-deflection-rate', 'knowledge-base-deflection', 'support-automation'],
    faqs: [
      { q: 'What is the difference between support deflection and ticket deflection rate?', a: 'Support deflection is the strategy. Ticket deflection rate is the metric that measures how often the strategy prevents agent-handled tickets.' },
      { q: 'When does support deflection hurt the customer experience?', a: 'When urgent technical issues get routed through self-serve loops instead of reaching a team that can investigate production data quickly.' },
    ],
  },
}
