import { useState } from 'react'
import { motion } from 'framer-motion'
import Card from '../components/Card'
import Button from '../components/Button'

const LLMSTxtGenerator = () => {
  const [formData, setFormData] = useState({
    companyName: '',
    website: '',
    description: '',
    products: '',
    keywords: '',
  })

  const [generatedContent, setGeneratedContent] = useState('')

  const handleChange = (e) => {
    const { name, value } = e.target
    setFormData(prev => ({ ...prev, [name]: value }))
  }

  const generateLLMSTxt = () => {
    const { companyName, website, description, products, keywords } = formData
    
    const content = `# ${companyName}

> ${description}

## About
${companyName} is accessible at ${website}

## Products & Services
${products}

## Keywords
${keywords}

## Contact
Website: ${website}

---
Generated by AltorLab llms.txt Generator
`
    setGeneratedContent(content)
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedContent)
    alert('Copied to clipboard!')
  }

  const downloadFile = () => {
    const element = document.createElement('a')
    const file = new Blob([generatedContent], { type: 'text/plain' })
    element.href = URL.createObjectURL(file)
    element.download = 'llms.txt'
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  return (
    <div className="pt-20">
      {/* Hero Section */}
      <section className="section-padding">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center max-w-4xl mx-auto mb-16"
          >
            <h1 className="text-5xl md:text-6xl font-bold mb-6">
              llms.txt Generator
            </h1>
            <p className="text-xl text-gray-400 leading-relaxed">
              Create an AI-readable file that helps language models understand your business. 
              Improve your visibility in AI-powered search and recommendations.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Form Section */}
            <Card>
              <h2 className="text-2xl font-bold mb-6">Enter Your Information</h2>
              <form className="space-y-6">
                <div>
                  <label className="block text-sm font-medium mb-2">
                    Company Name *
                  </label>
                  <input
                    type="text"
                    name="companyName"
                    value={formData.companyName}
                    onChange={handleChange}
                    className="w-full px-4 py-3 bg-dark-400 border border-gray-700 rounded-lg focus:outline-none focus:border-primary-500 transition-colors"
                    placeholder="AltorLab"
                    required
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium mb-2">
                    Website URL *
                  </label>
                  <input
                    type="url"
                    name="website"
                    value={formData.website}
                    onChange={handleChange}
                    className="w-full px-4 py-3 bg-dark-400 border border-gray-700 rounded-lg focus:outline-none focus:border-primary-500 transition-colors"
                    placeholder="https://altorlab.com"
                    required
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium mb-2">
                    Company Description *
                  </label>
                  <textarea
                    name="description"
                    value={formData.description}
                    onChange={handleChange}
                    rows="3"
                    className="w-full px-4 py-3 bg-dark-400 border border-gray-700 rounded-lg focus:outline-none focus:border-primary-500 transition-colors resize-none"
                    placeholder="Building tools for AI-native teams..."
                    required
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium mb-2">
                    Products & Services *
                  </label>
                  <textarea
                    name="products"
                    value={formData.products}
                    onChange={handleChange}
                    rows="4"
                    className="w-full px-4 py-3 bg-dark-400 border border-gray-700 rounded-lg focus:outline-none focus:border-primary-500 transition-colors resize-none"
                    placeholder="- llms.txt Generator&#10;- AI Insights Dashboard&#10;- AI Adoption Consulting"
                    required
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium mb-2">
                    Keywords (comma-separated)
                  </label>
                  <input
                    type="text"
                    name="keywords"
                    value={formData.keywords}
                    onChange={handleChange}
                    className="w-full px-4 py-3 bg-dark-400 border border-gray-700 rounded-lg focus:outline-none focus:border-primary-500 transition-colors"
                    placeholder="AI, machine learning, business tools, automation"
                  />
                </div>

                <Button
                  onClick={(e) => {
                    e.preventDefault()
                    generateLLMSTxt()
                  }}
                  className="w-full"
                  disabled={!formData.companyName || !formData.website || !formData.description || !formData.products}
                >
                  Generate llms.txt
                </Button>
              </form>
            </Card>

            {/* Preview Section */}
            <Card>
              <div className="flex justify-between items-center mb-6">
                <h2 className="text-2xl font-bold">Preview</h2>
                {generatedContent && (
                  <div className="flex gap-2">
                    <button
                      onClick={copyToClipboard}
                      className="px-3 py-1 text-sm bg-dark-400 border border-gray-700 rounded hover:border-gray-600 transition-colors"
                    >
                      Copy
                    </button>
                    <button
                      onClick={downloadFile}
                      className="px-3 py-1 text-sm bg-primary-600 text-white rounded hover:bg-primary-700 transition-colors"
                    >
                      Download
                    </button>
                  </div>
                )}
              </div>
              
              <div className="bg-dark-400 border border-gray-700 rounded-lg p-6 min-h-[400px] font-mono text-sm overflow-auto">
                {generatedContent ? (
                  <pre className="whitespace-pre-wrap text-gray-300">{generatedContent}</pre>
                ) : (
                  <div className="text-gray-500 text-center py-20">
                    Fill out the form and click "Generate llms.txt" to see your preview
                  </div>
                )}
              </div>
            </Card>
          </div>
        </div>
      </section>

      {/* Info Section */}
      <section className="section-padding bg-dark-300/50">
        <div className="container-custom max-w-4xl">
          <h2 className="text-3xl font-bold mb-8 text-center">What is llms.txt?</h2>
          <div className="space-y-6 text-gray-400 leading-relaxed">
            <p>
              llms.txt is a standardized markdown file that helps AI language models understand your 
              website and business. When AI assistants like ChatGPT, Claude, or Gemini need to answer 
              questions about your company, they can reference this file for accurate information.
            </p>
            <p>
              By creating an llms.txt file, you're making it easier for AI to:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Accurately describe your products and services</li>
              <li>Recommend your business when relevant</li>
              <li>Provide correct contact information</li>
              <li>Understand your company's mission and values</li>
            </ul>
            <p>
              Simply place the generated llms.txt file in the root directory of your website 
              (e.g., https://yourwebsite.com/llms.txt) to make it accessible to AI models.
            </p>
          </div>
        </div>
      </section>
    </div>
  )
}

export default LLMSTxtGenerator

